apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169710129
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169710129
    app.kubernetes.io/part-of: test-app-169710129
  name: java-quarkus-169710129
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169710129
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169710129
    spec:
      containers:
      - image: quay.io/hacdev/2h8mfdsd-tenant/test-app-169710129/java-quarkus-169710129@sha256:21522e707305f5d993314cb14fa99647e02661baaeeb7e54ae6ed20bbb281965
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
